---
- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: selinux.yml
  when: nginx_configure_selinux and ansible_os_family == "RedHat"

- include: "install-{{ ansible_os_family }}.yml"

- include: ensure-directories.yml

- include: configure.yml

- name: Enable and start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
    use: service
  when: nginx_enable|bool

- name: Disable service
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: false
  when: not nginx_enable
