---
- name: Install Python packages to SELinux (RHEL 7)
  ansible.builtin.yum:
    name:
      - libselinux-python
      - libsemanage-python
    state: present
  register: selinux_install
  until: selinux_install.rc == 0
  retries: 2
  delay: 10
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8",'<')


- name: Install Python packages to SELinux (RHEL 8)
  ansible.builtin.yum:
    name:
      - python3-libselinux
      - python3-libsemanage
    state: present
  register: selinux_install
  until: selinux_install.rc == 0
  retries: 2
  delay: 10
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("7",'>')

- name: Disable SELinux
  selinux:
    state: disabled
