---
- name: Check syntax
  ansible.builtin.shell: "nginx -t"
  changed_when: false
  check_mode: false
  listen:
    - Reload nginx
    - Restart nginx

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_enable|bool

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_enable|bool
